# Generated by Django 4.1.7 on 2023-03-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrador',
            name='data',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='registrador',
            name='nomeuser',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registrador',
            name='rep_dep',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
