# Generated by Django 4.1.7 on 2023-03-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_registrador_data_alter_registrador_nomeuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrador',
            options={'verbose_name': 'Registradore'},
        ),
        migrations.AlterField(
            model_name='registrador',
            name='tipo',
            field=models.CharField(choices=[('D', 'deputado'), ('A', 'acessor')], default='D', max_length=1),
        ),
    ]
