# Generated by Django 4.1.7 on 2023-03-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0003_alter_registrador_options_alter_registrador_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrador',
            name='tipo',
            field=models.CharField(choices=[('', ''), ('Deputado', 'deputado'), ('Acessor', 'acessor')], default='', max_length=8),
        ),
    ]
