# Generated by Django 4.1.7 on 2023-03-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0004_alter_registrador_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrador',
            name='locale_is',
            field=models.CharField(choices=[('', ''), ('Federal', 'Federal'), ('Estadual', 'Estadual')], default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='registrador',
            name='tipo',
            field=models.CharField(choices=[('', ''), ('Deputado', 'Deputado'), ('Acessor', 'Acessor')], default='', max_length=8),
        ),
    ]
