# Generated by Django 4.1.7 on 2023-03-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0005_registrador_locale_is_alter_registrador_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrador',
            name='is_writable',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
