# Generated by Django 4.1.7 on 2023-03-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0006_alter_registrador_is_writable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrador',
            name='rep_dep',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
